[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x7f7f7f"
blue = "0x5c5cff"
cyan = "0x00ffff"
green = "0x00ff00"
magenta = "0xff00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xffff00"

[colors.normal]
black = "0x000000"
blue = "0x0000ee"
cyan = "0x00cdcd"
green = "0x00cd00"
magenta = "0xcd00cd"
red = "0xcd0000"
white = "0xe5e5e5"
yellow = "0xcdcd00"

[colors.primary]
background = "#1b1b13"
foreground = "#c5c8c6"

[font]
#size = 11.0
#size = 15.0
size = 9.0

[font.normal]
family = "Inconsolata"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[window.padding]
x = 2
y = 2

[debug]
#render_timer=true
renderer="Gles2"
